# Generated by Django 3.2.13 on 2022-06-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Cafe')),
                ('rating', models.FloatField(help_text='Rating 1-5', max_length=1, verbose_name='Rating')),
                ('distance', models.CharField(help_text='Isi dalam satuan kilometer (KM)', max_length=100, verbose_name='Jarak')),
                ('long', models.CharField(max_length=50, verbose_name='Longtitude')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitude')),
                ('gmaps', models.CharField(help_text='Isi dengan link google maps cafe', max_length=120, verbose_name='Google Maps Link')),
            ],
        ),
    ]
