# Generated by Django 3.2.13 on 2022-06-03 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafes',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafes',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Updated At'),
        ),
    ]
