# Generated by Django 3.2.13 on 2022-06-03 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0002_auto_20220603_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafes',
            name='is_open_24h',
            field=models.BooleanField(default=False, verbose_name='Buka 24 Jam'),
        ),
        migrations.CreateModel(
            name='CafeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.cafes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CafePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Gambar')),
                ('promo_title', models.CharField(max_length=100, verbose_name='Judul (Title) Promo')),
                ('promo_text', models.TextField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.cafes')),
            ],
        ),
    ]
