# Generated by Django 3.2.13 on 2022-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20220608_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='Profile Picture'),
        ),
    ]
