# Generated by Django 3.2.13 on 2022-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_reviewer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafes',
            name='address',
            field=models.CharField(max_length=120, null=True, verbose_name='Alamat'),
        ),
    ]
