# Generated by Django 3.2.13 on 2022-06-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_cafes_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafes',
            name='desc',
            field=models.TextField(null=True, verbose_name='Deskripsi'),
        ),
    ]
